-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 20:24:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idproveedores` INT NOT NULL,
  `Razonsocial` VARCHAR(45) NULL,
  `RUC` VARCHAR(45) NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almacen` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(200) NULL,
  `cantidad` INT NULL,
  `Almacencol` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenCompra` (
  `idOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(15) NULL,
  `FechaEmicion` DATE NULL,
  `FechaAprovavion` DATE NULL,
  `total` DECIMAL(9,2) NULL,
  `proveedores_idproveedores` INT NOT NULL,
  `proveedor_idproveedores` INT NOT NULL,
  `Almacen_idProducto` INT NOT NULL,
  PRIMARY KEY (`idOrdenCompra`, `proveedores_idproveedores`),
  INDEX `fk_OrdenCompra_proveedor1_idx` (`proveedor_idproveedores` ASC),
  INDEX `fk_OrdenCompra_Almacen1_idx` (`Almacen_idProducto` ASC),
  CONSTRAINT `fk_OrdenCompra_proveedor1`
    FOREIGN KEY (`proveedor_idproveedores`)
    REFERENCES `mydb`.`proveedor` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenCompra_Almacen1`
    FOREIGN KEY (`Almacen_idProducto`)
    REFERENCES `mydb`.`Almacen` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitante` (
  `idsolicitante` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidopaterno` VARCHAR(200) NULL,
  `Apellido materno` VARCHAR(200) NULL,
  `EstadoCivil` VARCHAR(1) NULL,
  `Email` VARCHAR(45) NULL,
  `solicitantecol` VARCHAR(45) NULL,
  `RUC` VARCHAR(11) NULL,
  `OrdenCompra_idOrdenCompra` INT NOT NULL,
  PRIMARY KEY (`idsolicitante`),
  INDEX `fk_solicitante_OrdenCompra_idx` (`OrdenCompra_idOrdenCompra` ASC),
  CONSTRAINT `fk_solicitante_OrdenCompra`
    FOREIGN KEY (`OrdenCompra_idOrdenCompra`)
    REFERENCES `mydb`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(200) NULL,
  `Precio` INT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleOrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleOrdenCompra` (
  `idDetalleOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NULL,
  `DetalleOrdenCompra` VARCHAR(45) NULL,
  `Precio` DECIMAL(9,2) NULL,
  `cantidad` INT NULL,
  `OrdenCompra_idOrdenCompra` INT NOT NULL,
  `OrdenCompra_proveedores_idproveedores` INT NOT NULL,
  PRIMARY KEY (`idDetalleOrdenCompra`),
  INDEX `fk_DetalleOrdenCompra_OrdenCompra1_idx` (`OrdenCompra_idOrdenCompra` ASC, `OrdenCompra_proveedores_idproveedores` ASC),
  CONSTRAINT `fk_DetalleOrdenCompra_OrdenCompra1`
    FOREIGN KEY (`OrdenCompra_idOrdenCompra` , `OrdenCompra_proveedores_idproveedores`)
    REFERENCES `mydb`.`OrdenCompra` (`idOrdenCompra` , `proveedores_idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleOrdenCompraProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleOrdenCompraProducto` (
  `DetalleOrdenCompra_idDetalleOrdenCompra` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `hora` TIME NULL,
  `DetalleOrdenCompracol1` VARCHAR(45) NOT NULL,
  INDEX `fk_DetalleOrdenCompra_DetalleOrdenCompra1_idx` (`DetalleOrdenCompra_idDetalleOrdenCompra` ASC),
  INDEX `fk_DetalleOrdenCompra_Producto1_idx` (`Producto_idProducto` ASC),
  PRIMARY KEY (`DetalleOrdenCompracol1`),
  CONSTRAINT `fk_DetalleOrdenCompra_DetalleOrdenCompra1`
    FOREIGN KEY (`DetalleOrdenCompra_idDetalleOrdenCompra`)
    REFERENCES `mydb`.`DetalleOrdenCompra` (`idDetalleOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleOrdenCompra_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
