-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 21:31:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HokageDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HokageDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HokageDB` DEFAULT CHARACTER SET utf8 ;
USE `HokageDB` ;

-- -----------------------------------------------------
-- Table `HokageDB`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`Servicio` (
  `Id servicio` INT NOT NULL AUTO_INCREMENT,
  `Entidadad` VARCHAR(100) NULL,
  `ubicacion` VARCHAR(100) NULL,
  `RUC` VARCHAR(11) NULL,
  `Nautorizacion` VARCHAR(10) NULL,
  PRIMARY KEY (`Id servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`Gasolinera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`Gasolinera` (
  `idGasolinera` INT NOT NULL,
  `Razon social` VARCHAR(50) NULL,
  `RUC` VARCHAR(11) NULL,
  `Ubicacion` VARCHAR(80) NULL,
  `Email` VARCHAR(80) NULL,
  `telefono` VARCHAR(9) NULL,
  `Gasolineracol` VARCHAR(45) NULL,
  `Encargado` VARCHAR(45) NULL,
  `cabeceraServicio_Id servicio` INT NOT NULL,
  PRIMARY KEY (`idGasolinera`),
  INDEX `fk_Gasolinera_cabeceraServicio1_idx` (`cabeceraServicio_Id servicio` ASC) ,
  CONSTRAINT `fk_Gasolinera_cabeceraServicio1`
    FOREIGN KEY (`cabeceraServicio_Id servicio`)
    REFERENCES `HokageDB`.`Servicio` (`Id servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`proveedor` (
  `idproveedor` INT NOT NULL,
  `RUC` VARCHAR(45) NULL,
  `Gasolinera_idGasolinera` INT NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_Gasolinera1_idx` (`Gasolinera_idGasolinera` ASC) ,
  CONSTRAINT `fk_proveedor_Gasolinera1`
    FOREIGN KEY (`Gasolinera_idGasolinera`)
    REFERENCES `HokageDB`.`Gasolinera` (`idGasolinera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`detalle servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`detalle servicio` (
  `iddetalle servicio` INT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `cantidad` VARCHAR(45) NULL,
  `preciototal` VARCHAR(45) NULL,
  `cabeceraServicio_Id servicio` INT NOT NULL,
  PRIMARY KEY (`iddetalle servicio`),
  INDEX `fk_detalle servicio_cabeceraServicio1_idx` (`cabeceraServicio_Id servicio` ASC) ,
  CONSTRAINT `fk_detalle servicio_cabeceraServicio1`
    FOREIGN KEY (`cabeceraServicio_Id servicio`)
    REFERENCES `HokageDB`.`Servicio` (`Id servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `RUC` VARCHAR(11) NULL,
  `cabeceraServicio_Id servicio` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_cabeceraServicio_idx` (`cabeceraServicio_Id servicio` ASC) ,
  CONSTRAINT `fk_Cliente_cabeceraServicio`
    FOREIGN KEY (`cabeceraServicio_Id servicio`)
    REFERENCES `HokageDB`.`Servicio` (`Id servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`Combustibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`Combustibles` (
  `idCombustibles` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `Octanaje` VARCHAR(45) NULL,
  `precio` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idCombustibles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`almacen` (
  `idalmacen` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `capacidad` VARCHAR(6) NULL,
  `Gasolinera_idGasolinera` INT NOT NULL,
  `condicion` VARCHAR(45) NULL,
  PRIMARY KEY (`idalmacen`),
  INDEX `fk_almacen_Gasolinera1_idx` (`Gasolinera_idGasolinera` ASC) ,
  CONSTRAINT `fk_almacen_Gasolinera1`
    FOREIGN KEY (`Gasolinera_idGasolinera`)
    REFERENCES `HokageDB`.`Gasolinera` (`idGasolinera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`almacenCombustbles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`almacenCombustbles` (
  `almacen_idalmacen` INT NOT NULL,
  `Combustibles_idCombustibles` INT NOT NULL,
  `almacenCombustblescol` VARCHAR(45) NOT NULL,
  INDEX `fk_almacenCombustbles_almacen1_idx` (`almacen_idalmacen` ASC) ,
  INDEX `fk_almacenCombustbles_Combustibles1_idx` (`Combustibles_idCombustibles` ASC) ,
  PRIMARY KEY (`almacenCombustblescol`),
  CONSTRAINT `fk_almacenCombustbles_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `HokageDB`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almacenCombustbles_Combustibles1`
    FOREIGN KEY (`Combustibles_idCombustibles`)
    REFERENCES `HokageDB`.`Combustibles` (`idCombustibles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`personal` (
  `idpersonal` INT NOT NULL,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `DNI` VARCHAR(8) NULL,
  `cargo` VARCHAR(45) NULL,
  `Email` VARCHAR(80) NULL,
  `telefono` VARCHAR(9) NULL,
  `Gasolinera_idGasolinera` INT NOT NULL,
  PRIMARY KEY (`idpersonal`),
  INDEX `fk_personal_Gasolinera1_idx` (`Gasolinera_idGasolinera` ASC) ,
  CONSTRAINT `fk_personal_Gasolinera1`
    FOREIGN KEY (`Gasolinera_idGasolinera`)
    REFERENCES `HokageDB`.`Gasolinera` (`idGasolinera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`controlDeRecursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`controlDeRecursos` (
  `idcontrolDeRecursos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Detalles` VARCHAR(200) NULL,
  `Fecha` DATETIME NULL,
  `tipo de movimiento` TINYINT NULL,
  `saldo` DECIMAL(9,2) NULL,
  PRIMARY KEY (`idcontrolDeRecursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`ControlAlmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`ControlAlmacen` (
  `almacen_idalmacen` INT NOT NULL,
  `controlDeRecursos_idcontrolDeRecursos` INT NOT NULL,
  `ControlAlmacencol` VARCHAR(45) NOT NULL,
  INDEX `fk_table1_almacen1_idx` (`almacen_idalmacen` ASC) ,
  INDEX `fk_table1_controlDeRecursos1_idx` (`controlDeRecursos_idcontrolDeRecursos` ASC) ,
  PRIMARY KEY (`ControlAlmacencol`),
  CONSTRAINT `fk_table1_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `HokageDB`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_controlDeRecursos1`
    FOREIGN KEY (`controlDeRecursos_idcontrolDeRecursos`)
    REFERENCES `HokageDB`.`controlDeRecursos` (`idcontrolDeRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HokageDB`.`ControlServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HokageDB`.`ControlServicio` (
  `Servicio_Id servicio` INT NOT NULL,
  `controlDeRecursos_idcontrolDeRecursos` INT NOT NULL,
  `ControlServiciocol` VARCHAR(45) NOT NULL,
  INDEX `fk_table2_Servicio1_idx` (`Servicio_Id servicio` ASC) ,
  INDEX `fk_table2_controlDeRecursos1_idx` (`controlDeRecursos_idcontrolDeRecursos` ASC) ,
  PRIMARY KEY (`ControlServiciocol`),
  CONSTRAINT `fk_table2_Servicio1`
    FOREIGN KEY (`Servicio_Id servicio`)
    REFERENCES `HokageDB`.`Servicio` (`Id servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_controlDeRecursos1`
    FOREIGN KEY (`controlDeRecursos_idcontrolDeRecursos`)
    REFERENCES `HokageDB`.`controlDeRecursos` (`idcontrolDeRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
